removed duplicate allow and empty lines and spaces
ck2plus/CleanSlate pull request #206
Opened 2024-08-21 18:26 UTC by unique-usernames-are-annoying

2024-08-26 23:57 UTC, schwarherz requested changes
It looks like the encoding may have been changed in several files. I want to verify that the encoding is correct (Windows-1252) and that any malformed characters are corrected before approval. Otherwise the vast majority of these changes are whitespace-only and should be fine.

2024-08-26 23:57 UTC, schwarherz commented on CleanSlate/common/scripted_triggers/00_china_triggers.txt
Encoding seems to have changed on this file. Need to make sure it's corrected back to Windows-1252

2024-08-26 23:57 UTC, schwarherz commented on CleanSlate/events/base_religious_events.txt
> +# Written by Henrik F�hraeus, Johan Andersson & Niklas Strid
```suggestion
# Written by Henrik Fåhraeus, Johan Andersson & Niklas Strid
```

2024-08-26 23:57 UTC, schwarherz commented on CleanSlate/events/sunset_invasion.txt
> +# Written by Henrik F�hraeus and Henrik Eklund
```suggestion
# Written by Henrik Fåhraeus and Henrik Eklund
```

2024-08-26 23:58 UTC, schwarherz commented on CleanSlate/common/scripted_triggers/00_china_triggers.txt
> +			text = china_offmap_decisions_enabled_trigger_war_tt # "Is at peace with �Y[From.GetTitledFirstName]�!"
```suggestion
			text = china_offmap_decisions_enabled_trigger_war_tt # "Is at peace with §Y[From.GetTitledFirstName]§!"
```

2024-08-26 23:59 UTC, schwarherz commented on CleanSlate/common/scripted_triggers/00_china_triggers.txt
> +			text = china_offmap_decisions_enabled_trigger_war_tt # "Is at peace with �Y[From.GetTitledFirstName]�!"
```suggestion
			text = china_offmap_decisions_enabled_trigger_war_tt # "Is at peace with §Y[From.GetTitledFirstName]§!"
```

2024-08-27 06:17 UTC, unique-usernames-are-annoying commented on CleanSlate/common/scripted_triggers/00_china_triggers.txt
I looked at the 3 files mentioned, however when i open it either with the vscode setting "files.encoding": "windows1252" it gets shown properly and opening it without it, it gets opened with utf8 and reopening it with windows1252 shows everything correct. Though this is normal for Github desktop to show special characters encoded in windows1252 wrong, which is also the reason i suggested the settings you are currently trying to add in the other PR.

2024-09-06 06:59 UTC, schwarherz commented
Created new branch on origin for these so that I could rebase the request onto main

2024-09-06 06:59 UTC, closed without merging